version: "3.8"

services:
  aequora:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        - PYTHON_VERSION=3.11   # build argument example (if needed)
    ports:
      - "5000:5000"
    environment:
      - fireflyIII_id=${FIREFLYIII_ID}
      - fireflyIII_secret=${FIREFLYIII_SECRET}
      - fireflyIII_url=${FIREFLYIII_URL}
      - FLASK_DEBUG=${FLASK_DEBUG:-False}  # default to False for production
    restart: unless-stopped
